# In _config.yml
title: Quantitative Bio-Image Analysis with Python Course Book
author: Bio-Image Analysis Technology Development Group - Physics of Life
logo: biapol_logo.png
execute:
  execute_notebooks: force

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

  # Information about where the book exists on the web
repository:
  url: https://github.com/BiAPoL/Quantitative_Bio_Image_Analysis_with_Python_2022  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true